"""add user_id to sessions

Revision ID: 3c11b17a5e99
Revises: d75e5e518abd
Create Date: 2026-03-18 00:39:24.082613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c11b17a5e99'
down_revision: Union[str, None] = 'd75e5e518abd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('user_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_column('sessions', 'user_id')
    # ### end Alembic commands ###
